import type { PrismaClient } from '../generated/prisma';

export async function seedArticles(prisma: PrismaClient) {
  const articles = [
    // ─── PRODUIT_FINI ─────────────────────────────────────
    {
      id: 'ART-PF-001',
      label: 'Trottinette Electrique',
      type: 'PRODUIT_FINI' as const,
      delaiJours: 3,
      coutUnitaire: 850.0,
      unite: 'piece',
    },

    // ─── SEMI_FINI ────────────────────────────────────────
    {
      id: 'ART-SF-001',
      label: 'Cadre + Plateau assemblé',
      type: 'SEMI_FINI' as const,
      delaiJours: 2,
      coutUnitaire: 180.0,
      unite: 'piece',
    },
    {
      id: 'ART-SF-002',
      label: 'Colonne + Guidon assemblé',
      type: 'SEMI_FINI' as const,
      delaiJours: 1.5,
      coutUnitaire: 120.0,
      unite: 'piece',
    },
    {
      id: 'ART-SF-003',
      label: 'Pack Batterie + Moteur',
      type: 'SEMI_FINI' as const,
      delaiJours: 2.5,
      coutUnitaire: 350.0,
      unite: 'piece',
    },

    // ─── ACHETE_COMMUN ────────────────────────────────────
    {
      id: 'ART-AC-001',
      label: 'Cadre aluminium',
      type: 'ACHETE_COMMUN' as const,
      delaiJours: 15,
      coutUnitaire: 65.0,
      unite: 'piece',
    },
    {
      id: 'ART-AC-002',
      label: 'Roue avant 8"',
      type: 'ACHETE_COMMUN' as const,
      delaiJours: 10,
      coutUnitaire: 22.0,
      unite: 'piece',
    },
    {
      id: 'ART-AC-003',
      label: 'Roue arrière 8"',
      type: 'ACHETE_COMMUN' as const,
      delaiJours: 10,
      coutUnitaire: 22.0,
      unite: 'piece',
    },
    {
      id: 'ART-AC-004',
      label: 'Kit freinage',
      type: 'ACHETE_COMMUN' as const,
      delaiJours: 12,
      coutUnitaire: 35.0,
      unite: 'piece',
    },
    {
      id: 'ART-AC-005',
      label: 'Kit éclairage LED',
      type: 'ACHETE_COMMUN' as const,
      delaiJours: 8,
      coutUnitaire: 18.0,
      unite: 'piece',
    },
    {
      id: 'ART-AC-006',
      label: 'Contrôleur électronique',
      type: 'ACHETE_COMMUN' as const,
      delaiJours: 20,
      coutUnitaire: 55.0,
      unite: 'piece',
    },
    {
      id: 'ART-AC-007',
      label: 'Faisceau électrique',
      type: 'ACHETE_COMMUN' as const,
      delaiJours: 10,
      coutUnitaire: 12.0,
      unite: 'piece',
    },
    {
      id: 'ART-AC-008',
      label: 'Visserie inox (lot)',
      type: 'ACHETE_COMMUN' as const,
      delaiJours: 5,
      coutUnitaire: 8.0,
      unite: 'lot',
    },
    {
      id: 'ART-AC-009',
      label: "Joint d'étanchéité (lot)",
      type: 'ACHETE_COMMUN' as const,
      delaiJours: 5,
      coutUnitaire: 4.5,
      unite: 'lot',
    },
    {
      id: 'ART-AC-010',
      label: 'Grip poignée',
      type: 'ACHETE_COMMUN' as const,
      delaiJours: 7,
      coutUnitaire: 6.0,
      unite: 'paire',
    },
    {
      id: 'ART-AC-011',
      label: 'Béquille rétractable',
      type: 'ACHETE_COMMUN' as const,
      delaiJours: 8,
      coutUnitaire: 9.0,
      unite: 'piece',
    },
    {
      id: 'ART-AC-012',
      label: 'Garde-boue AV+AR',
      type: 'ACHETE_COMMUN' as const,
      delaiJours: 10,
      coutUnitaire: 14.0,
      unite: 'jeu',
    },
    {
      id: 'ART-AC-013',
      label: 'Sonnette + réflecteurs',
      type: 'ACHETE_COMMUN' as const,
      delaiJours: 5,
      coutUnitaire: 5.0,
      unite: 'kit',
    },

    // ─── ACHETE_SPECIFIQUE ────────────────────────────────
    {
      id: 'ART-AS-001',
      label: 'Plateau couleur rouge',
      type: 'ACHETE_SPECIFIQUE' as const,
      delaiJours: 12,
      coutUnitaire: 28.0,
      unite: 'piece',
    },
    {
      id: 'ART-AS-002',
      label: 'Plateau couleur bleu',
      type: 'ACHETE_SPECIFIQUE' as const,
      delaiJours: 12,
      coutUnitaire: 28.0,
      unite: 'piece',
    },
    {
      id: 'ART-AS-003',
      label: 'Plateau long (XL)',
      type: 'ACHETE_SPECIFIQUE' as const,
      delaiJours: 14,
      coutUnitaire: 42.0,
      unite: 'piece',
    },
    {
      id: 'ART-AS-004',
      label: 'Guidon sport',
      type: 'ACHETE_SPECIFIQUE' as const,
      delaiJours: 12,
      coutUnitaire: 38.0,
      unite: 'piece',
    },
    {
      id: 'ART-AS-005',
      label: 'Guidon confort',
      type: 'ACHETE_SPECIFIQUE' as const,
      delaiJours: 12,
      coutUnitaire: 42.0,
      unite: 'piece',
    },
    {
      id: 'ART-AS-006',
      label: 'Batterie 48V longue autonomie',
      type: 'ACHETE_SPECIFIQUE' as const,
      delaiJours: 25,
      coutUnitaire: 195.0,
      unite: 'piece',
    },
    {
      id: 'ART-AS-007',
      label: 'Batterie 36V standard',
      type: 'ACHETE_SPECIFIQUE' as const,
      delaiJours: 18,
      coutUnitaire: 120.0,
      unite: 'piece',
    },
    {
      id: 'ART-AS-008',
      label: 'Moteur 500W',
      type: 'ACHETE_SPECIFIQUE' as const,
      delaiJours: 20,
      coutUnitaire: 145.0,
      unite: 'piece',
    },
    {
      id: 'ART-AS-009',
      label: 'Moteur 350W',
      type: 'ACHETE_SPECIFIQUE' as const,
      delaiJours: 15,
      coutUnitaire: 105.0,
      unite: 'piece',
    },
    {
      id: 'ART-AS-010',
      label: 'Pneu tout-terrain',
      type: 'ACHETE_SPECIFIQUE' as const,
      delaiJours: 10,
      coutUnitaire: 32.0,
      unite: 'paire',
    },
    {
      id: 'ART-AS-011',
      label: 'Porte-bagages arrière',
      type: 'ACHETE_SPECIFIQUE' as const,
      delaiJours: 8,
      coutUnitaire: 24.0,
      unite: 'piece',
    },
    {
      id: 'ART-AS-012',
      label: 'Éclairage premium',
      type: 'ACHETE_SPECIFIQUE' as const,
      delaiJours: 10,
      coutUnitaire: 35.0,
      unite: 'piece',
    },
  ];

  await prisma.article.createMany({ data: articles });
  console.log(`  -> ${articles.length} articles created`);

  return articles;
}
